### ISSUE TITLE
Usage instructions of this repo

### ISSUE THREAD

**Issue by sjdrc** [1582130940/android_vendor_gapps#1]
Hi there, I've been on the hunt for a way to integrate gapps into my build of AOSP. Is adding your repo to the manifest and including ```$(call inherit-product, vendor/gapps/config.mk)``` into the vendor common makefile all I need to do to build it?

P.S. Thanks very much for putting this on github! I've been looking for something like this for a while :)

**Comment by 1582130940** [comment]
After adding the call, compile it according to the steps of compiling the ROM.
